name: "Publish"
on:
  create:
    branches:
      - master

jobs:
  release:
    name: Publish GitHub Actions to Marketplace
    runs-on: ubuntu-latest
    steps:
      - name: Publish GitHub Actions to Marketplace
        uses: technote-space/release-github-actions@v7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_NAME: 'GP'
          COMMIT_EMAIL: 'me@httgp.com'
          CREATE_MAJOR_VERSION_TAG: false
          CREATE_MINOR_VERSION_TAG: false
          CLEAN_TARGETS: '.[!.]*,test,src,*.ts,*.json,CHANGELOG.md,_config.yml'
